include:
  - board: nice_nano//zmk
    shield: dactyl_manuform_left
    artifact-name: dactyl_manuform_left-nice_nano_zmk
  - board: nice_nano//zmk
    shield: dactyl_manuform_right
    artifact-name: dactyl_manuform_right-nice_nano_zmk
